### ISSUE TITLE
Feature request: option to disable output buffer

### ISSUE THREAD

**Issue by ddugovic** [lucasart/c-chess-cli#10]
I don't undersatnd why on Travis, output is buffering (so I am limited to ~10 games of duration 10+0.1 else Travis times out):
https://travis-ci.org/github/ddugovic/Stockfish/jobs/698274760#L429

**Comment by lucasart** [comment]
Buffering on stdout is left at its default value, which is line buffering. If there is nothing to print to stdout, because no game was completed, then nothing will be printed, regardless of buffering. All you achieve by disabling buffering is to slow things down.

So I don't think disabling buffering will solve your problem. If you want to find out for sure, you can disable by adding this line at the beginning of `main()` in main.c:
```
setvbuf(stdin, NULL, _IONBF, 0);
```
The problem is more likely on Travis side. What is the timeout logic exactly ? All I see is:
`The command "../tests/play.sh" exited with 0.` after 297.42 seconds. No indication of an error or timeout. And if there's a timeout, what makes you think it is between lines and not at command level ?

**Comment by ddugovic** [comment]
Thanks, I'll try that in my fork of c-chess-cli (or fix the Travis timeout configuration).

Here's the previous run where I had attempted to play 100 games instead of 10.  When I ran the same script locally in an interactive shell, I observed output (and from the 10-game run, I also observed output once the match ended):
https://travis-ci.org/github/ddugovic/Stockfish/jobs/698262717#L429
