### ISSUE TITLE
Add support for custom chess variants

### ISSUE THREAD

**Issue by inversed-ru** [lucasart/c-chess-cli#59]
I am trying to generate self-play data using Fairy Stockfish and a custom chess variant. I thought I just need to set a couple of engine options to select the variant. The problem is, c-chess-cli parses and validates the moves, so in the best case I get `[Termination "rules infraction"]` in the middle of a game. Is it possible to implement a mode in which move parsing is completely bypassed and the moves are just relayed between the engines as strings?

**Comment by lucasart** [comment]
No, it's impossible. That's because c-chess-cli must understand moves and update internal board (and hash stack) representation. You could by pass all this, but not a trivial change, and you would have to extend the UCI protocol to ask engine about game terminal conditions, and just assume engines can be trusted to play legal moves.

**Comment by lucasart** [comment]
I mean you could do this (in your fork) but you'd have to butcher the code logic in ways I don't want to commit to this repo.
